//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NaturalUncertaintyCsharpApi {

public class Alternative : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Alternative(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Alternative obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Alternative obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Alternative() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          natural_uncertainty_libPINVOKE.delete_Alternative(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Alternative(string name, DoubleList marks) : this(natural_uncertainty_libPINVOKE.new_Alternative(name, DoubleList.getCPtr(marks)), true) {
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getName() {
    string ret = natural_uncertainty_libPINVOKE.Alternative_getName(swigCPtr);
    return ret;
  }

  public DoubleList getMarks() {
    DoubleList ret = new DoubleList(natural_uncertainty_libPINVOKE.Alternative_getMarks(swigCPtr), true);
    return ret;
  }

  public void setMarks(DoubleList marks) {
    natural_uncertainty_libPINVOKE.Alternative_setMarks(swigCPtr, DoubleList.getCPtr(marks));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public double minMark() {
    double ret = natural_uncertainty_libPINVOKE.Alternative_minMark(swigCPtr);
    return ret;
  }

  public double maxMark() {
    double ret = natural_uncertainty_libPINVOKE.Alternative_maxMark(swigCPtr);
    return ret;
  }

  public double sumOfMarks() {
    double ret = natural_uncertainty_libPINVOKE.Alternative_sumOfMarks(swigCPtr);
    return ret;
  }

  public double avgOfMarks() {
    double ret = natural_uncertainty_libPINVOKE.Alternative_avgOfMarks(swigCPtr);
    return ret;
  }

}

}
