//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NaturalUncertaintyCsharpApi {

class libnatural_uncertaintyPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="SWIGRegisterExceptionCallbacks_libnatural_uncertainty")]
    public static extern void SWIGRegisterExceptionCallbacks_libnatural_uncertainty(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_libnatural_uncertainty")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_libnatural_uncertainty(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_libnatural_uncertainty(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_libnatural_uncertainty(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="SWIGRegisterStringCallback_libnatural_uncertainty")]
    public static extern void SWIGRegisterStringCallback_libnatural_uncertainty(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_libnatural_uncertainty(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static libnatural_uncertaintyPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_DoubleList__SWIG_0")]
  public static extern global::System.IntPtr new_DoubleList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_DoubleList__SWIG_1")]
  public static extern global::System.IntPtr new_DoubleList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_Clear")]
  public static extern void DoubleList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_Add")]
  public static extern void DoubleList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_size")]
  public static extern uint DoubleList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_empty")]
  public static extern bool DoubleList_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_capacity")]
  public static extern uint DoubleList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_reserve")]
  public static extern void DoubleList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_DoubleList__SWIG_2")]
  public static extern global::System.IntPtr new_DoubleList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_getitemcopy")]
  public static extern double DoubleList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_getitem")]
  public static extern double DoubleList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_setitem")]
  public static extern void DoubleList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_AddRange")]
  public static extern void DoubleList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_GetRange")]
  public static extern global::System.IntPtr DoubleList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_Insert")]
  public static extern void DoubleList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_InsertRange")]
  public static extern void DoubleList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_RemoveAt")]
  public static extern void DoubleList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_RemoveRange")]
  public static extern void DoubleList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_Repeat")]
  public static extern global::System.IntPtr DoubleList_Repeat(double jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_Reverse__SWIG_0")]
  public static extern void DoubleList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_Reverse__SWIG_1")]
  public static extern void DoubleList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_SetRange")]
  public static extern void DoubleList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_Contains")]
  public static extern bool DoubleList_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_IndexOf")]
  public static extern int DoubleList_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_LastIndexOf")]
  public static extern int DoubleList_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_DoubleList_Remove")]
  public static extern bool DoubleList_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_DoubleList")]
  public static extern void delete_DoubleList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_StringList__SWIG_0")]
  public static extern global::System.IntPtr new_StringList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_StringList__SWIG_1")]
  public static extern global::System.IntPtr new_StringList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_Clear")]
  public static extern void StringList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_Add")]
  public static extern void StringList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_size")]
  public static extern uint StringList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_empty")]
  public static extern bool StringList_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_capacity")]
  public static extern uint StringList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_reserve")]
  public static extern void StringList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_StringList__SWIG_2")]
  public static extern global::System.IntPtr new_StringList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_getitemcopy")]
  public static extern string StringList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_getitem")]
  public static extern string StringList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_setitem")]
  public static extern void StringList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_AddRange")]
  public static extern void StringList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_GetRange")]
  public static extern global::System.IntPtr StringList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_Insert")]
  public static extern void StringList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_InsertRange")]
  public static extern void StringList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_RemoveAt")]
  public static extern void StringList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_RemoveRange")]
  public static extern void StringList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_Repeat")]
  public static extern global::System.IntPtr StringList_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_Reverse__SWIG_0")]
  public static extern void StringList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_Reverse__SWIG_1")]
  public static extern void StringList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_SetRange")]
  public static extern void StringList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_Contains")]
  public static extern bool StringList_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_IndexOf")]
  public static extern int StringList_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_LastIndexOf")]
  public static extern int StringList_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_StringList_Remove")]
  public static extern bool StringList_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_StringList")]
  public static extern void delete_StringList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_IntList__SWIG_0")]
  public static extern global::System.IntPtr new_IntList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_IntList__SWIG_1")]
  public static extern global::System.IntPtr new_IntList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_Clear")]
  public static extern void IntList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_Add")]
  public static extern void IntList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_size")]
  public static extern uint IntList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_empty")]
  public static extern bool IntList_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_capacity")]
  public static extern uint IntList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_reserve")]
  public static extern void IntList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_IntList__SWIG_2")]
  public static extern global::System.IntPtr new_IntList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_getitemcopy")]
  public static extern int IntList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_getitem")]
  public static extern int IntList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_setitem")]
  public static extern void IntList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_AddRange")]
  public static extern void IntList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_GetRange")]
  public static extern global::System.IntPtr IntList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_Insert")]
  public static extern void IntList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_InsertRange")]
  public static extern void IntList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_RemoveAt")]
  public static extern void IntList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_RemoveRange")]
  public static extern void IntList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_Repeat")]
  public static extern global::System.IntPtr IntList_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_Reverse__SWIG_0")]
  public static extern void IntList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_Reverse__SWIG_1")]
  public static extern void IntList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_SetRange")]
  public static extern void IntList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_Contains")]
  public static extern bool IntList_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_IndexOf")]
  public static extern int IntList_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_LastIndexOf")]
  public static extern int IntList_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_IntList_Remove")]
  public static extern bool IntList_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_IntList")]
  public static extern void delete_IntList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_TaskProcess__SWIG_0")]
  public static extern global::System.IntPtr new_TaskProcess__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_TaskProcess__SWIG_1")]
  public static extern global::System.IntPtr new_TaskProcess__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_Clear")]
  public static extern void TaskProcess_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_Add")]
  public static extern void TaskProcess_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_size")]
  public static extern uint TaskProcess_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_empty")]
  public static extern bool TaskProcess_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_capacity")]
  public static extern uint TaskProcess_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_reserve")]
  public static extern void TaskProcess_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_TaskProcess__SWIG_2")]
  public static extern global::System.IntPtr new_TaskProcess__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_getitemcopy")]
  public static extern global::System.IntPtr TaskProcess_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_getitem")]
  public static extern global::System.IntPtr TaskProcess_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_setitem")]
  public static extern void TaskProcess_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_AddRange")]
  public static extern void TaskProcess_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_GetRange")]
  public static extern global::System.IntPtr TaskProcess_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_Insert")]
  public static extern void TaskProcess_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_InsertRange")]
  public static extern void TaskProcess_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_RemoveAt")]
  public static extern void TaskProcess_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_RemoveRange")]
  public static extern void TaskProcess_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_Repeat")]
  public static extern global::System.IntPtr TaskProcess_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_Reverse__SWIG_0")]
  public static extern void TaskProcess_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_Reverse__SWIG_1")]
  public static extern void TaskProcess_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_SetRange")]
  public static extern void TaskProcess_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_Contains")]
  public static extern bool TaskProcess_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_IndexOf")]
  public static extern int TaskProcess_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_LastIndexOf")]
  public static extern int TaskProcess_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskProcess_Remove")]
  public static extern bool TaskProcess_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_TaskProcess")]
  public static extern void delete_TaskProcess(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_AlternativeList__SWIG_0")]
  public static extern global::System.IntPtr new_AlternativeList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_AlternativeList__SWIG_1")]
  public static extern global::System.IntPtr new_AlternativeList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_Clear")]
  public static extern void AlternativeList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_Add")]
  public static extern void AlternativeList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_size")]
  public static extern uint AlternativeList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_empty")]
  public static extern bool AlternativeList_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_capacity")]
  public static extern uint AlternativeList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_reserve")]
  public static extern void AlternativeList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_AlternativeList__SWIG_2")]
  public static extern global::System.IntPtr new_AlternativeList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_getitemcopy")]
  public static extern global::System.IntPtr AlternativeList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_getitem")]
  public static extern global::System.IntPtr AlternativeList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_setitem")]
  public static extern void AlternativeList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_AddRange")]
  public static extern void AlternativeList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_GetRange")]
  public static extern global::System.IntPtr AlternativeList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_Insert")]
  public static extern void AlternativeList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_InsertRange")]
  public static extern void AlternativeList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_RemoveAt")]
  public static extern void AlternativeList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_RemoveRange")]
  public static extern void AlternativeList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_Repeat")]
  public static extern global::System.IntPtr AlternativeList_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_Reverse__SWIG_0")]
  public static extern void AlternativeList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_Reverse__SWIG_1")]
  public static extern void AlternativeList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AlternativeList_SetRange")]
  public static extern void AlternativeList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_AlternativeList")]
  public static extern void delete_AlternativeList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_ProbabilisticAlternativeList__SWIG_0")]
  public static extern global::System.IntPtr new_ProbabilisticAlternativeList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_ProbabilisticAlternativeList__SWIG_1")]
  public static extern global::System.IntPtr new_ProbabilisticAlternativeList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_Clear")]
  public static extern void ProbabilisticAlternativeList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_Add")]
  public static extern void ProbabilisticAlternativeList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_size")]
  public static extern uint ProbabilisticAlternativeList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_empty")]
  public static extern bool ProbabilisticAlternativeList_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_capacity")]
  public static extern uint ProbabilisticAlternativeList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_reserve")]
  public static extern void ProbabilisticAlternativeList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_ProbabilisticAlternativeList__SWIG_2")]
  public static extern global::System.IntPtr new_ProbabilisticAlternativeList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_getitemcopy")]
  public static extern global::System.IntPtr ProbabilisticAlternativeList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_getitem")]
  public static extern global::System.IntPtr ProbabilisticAlternativeList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_setitem")]
  public static extern void ProbabilisticAlternativeList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_AddRange")]
  public static extern void ProbabilisticAlternativeList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_GetRange")]
  public static extern global::System.IntPtr ProbabilisticAlternativeList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_Insert")]
  public static extern void ProbabilisticAlternativeList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_InsertRange")]
  public static extern void ProbabilisticAlternativeList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_RemoveAt")]
  public static extern void ProbabilisticAlternativeList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_RemoveRange")]
  public static extern void ProbabilisticAlternativeList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_Repeat")]
  public static extern global::System.IntPtr ProbabilisticAlternativeList_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_Reverse__SWIG_0")]
  public static extern void ProbabilisticAlternativeList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_Reverse__SWIG_1")]
  public static extern void ProbabilisticAlternativeList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternativeList_SetRange")]
  public static extern void ProbabilisticAlternativeList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_ProbabilisticAlternativeList")]
  public static extern void delete_ProbabilisticAlternativeList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_UncertaintyList__SWIG_0")]
  public static extern global::System.IntPtr new_UncertaintyList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_UncertaintyList__SWIG_1")]
  public static extern global::System.IntPtr new_UncertaintyList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_Clear")]
  public static extern void UncertaintyList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_Add")]
  public static extern void UncertaintyList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_size")]
  public static extern uint UncertaintyList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_empty")]
  public static extern bool UncertaintyList_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_capacity")]
  public static extern uint UncertaintyList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_reserve")]
  public static extern void UncertaintyList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_UncertaintyList__SWIG_2")]
  public static extern global::System.IntPtr new_UncertaintyList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_getitemcopy")]
  public static extern global::System.IntPtr UncertaintyList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_getitem")]
  public static extern global::System.IntPtr UncertaintyList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_setitem")]
  public static extern void UncertaintyList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_AddRange")]
  public static extern void UncertaintyList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_GetRange")]
  public static extern global::System.IntPtr UncertaintyList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_Insert")]
  public static extern void UncertaintyList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_InsertRange")]
  public static extern void UncertaintyList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_RemoveAt")]
  public static extern void UncertaintyList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_RemoveRange")]
  public static extern void UncertaintyList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_Repeat")]
  public static extern global::System.IntPtr UncertaintyList_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_Reverse__SWIG_0")]
  public static extern void UncertaintyList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_Reverse__SWIG_1")]
  public static extern void UncertaintyList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyList_SetRange")]
  public static extern void UncertaintyList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_UncertaintyList")]
  public static extern void delete_UncertaintyList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_Alternative")]
  public static extern global::System.IntPtr new_Alternative(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Alternative_getName")]
  public static extern string Alternative_getName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Alternative_getMarks")]
  public static extern global::System.IntPtr Alternative_getMarks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Alternative_setMarks")]
  public static extern void Alternative_setMarks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Alternative_minMark")]
  public static extern double Alternative_minMark(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Alternative_maxMark")]
  public static extern double Alternative_maxMark(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Alternative_sumOfMarks")]
  public static extern double Alternative_sumOfMarks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Alternative_avgOfMarks")]
  public static extern double Alternative_avgOfMarks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_Alternative")]
  public static extern void delete_Alternative(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_Uncertainty")]
  public static extern global::System.IntPtr new_Uncertainty(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Uncertainty_getName")]
  public static extern string Uncertainty_getName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_Uncertainty")]
  public static extern void delete_Uncertainty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_ProbabilisticAlternative")]
  public static extern global::System.IntPtr new_ProbabilisticAlternative(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternative_isValid")]
  public static extern bool ProbabilisticAlternative_isValid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternative_getName")]
  public static extern string ProbabilisticAlternative_getName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternative_getMarks")]
  public static extern global::System.IntPtr ProbabilisticAlternative_getMarks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternative_getProbabilities")]
  public static extern global::System.IntPtr ProbabilisticAlternative_getProbabilities(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternative_setMarks")]
  public static extern void ProbabilisticAlternative_setMarks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternative_setProbabilities")]
  public static extern void ProbabilisticAlternative_setProbabilities(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticAlternative_getMathematicalExpectation")]
  public static extern double ProbabilisticAlternative_getMathematicalExpectation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_ProbabilisticAlternative")]
  public static extern void delete_ProbabilisticAlternative(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_MathModel__SWIG_0")]
  public static extern global::System.IntPtr new_MathModel__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_MathModel__SWIG_1")]
  public static extern global::System.IntPtr new_MathModel__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_MathModel__SWIG_2")]
  public static extern global::System.IntPtr new_MathModel__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_MathModel_setAlternatives")]
  public static extern void MathModel_setAlternatives(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_MathModel_setUncertainties")]
  public static extern void MathModel_setUncertainties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_MathModel_getAlternatives")]
  public static extern global::System.IntPtr MathModel_getAlternatives(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_MathModel_getUncertainties")]
  public static extern global::System.IntPtr MathModel_getUncertainties(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_MathModel_isValid")]
  public static extern bool MathModel_isValid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_MathModel")]
  public static extern void delete_MathModel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_ProbabilisticModel__SWIG_0")]
  public static extern global::System.IntPtr new_ProbabilisticModel__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_ProbabilisticModel__SWIG_1")]
  public static extern global::System.IntPtr new_ProbabilisticModel__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_ProbabilisticModel__SWIG_2")]
  public static extern global::System.IntPtr new_ProbabilisticModel__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticModel_setAlternatives")]
  public static extern void ProbabilisticModel_setAlternatives(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticModel_setUncertainties")]
  public static extern void ProbabilisticModel_setUncertainties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticModel_getAlternatives")]
  public static extern global::System.IntPtr ProbabilisticModel_getAlternatives(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticModel_getUncertainties")]
  public static extern global::System.IntPtr ProbabilisticModel_getUncertainties(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilisticModel_isValid")]
  public static extern bool ProbabilisticModel_isValid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_ProbabilisticModel")]
  public static extern void delete_ProbabilisticModel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Criterion_withLoggingProcess")]
  public static extern void Criterion_withLoggingProcess(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Criterion_getProcess")]
  public static extern global::System.IntPtr Criterion_getProcess(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_Criterion_solve")]
  public static extern global::System.IntPtr Criterion_solve(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_Criterion")]
  public static extern void delete_Criterion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_SolveStatus_OptimalDecisionResult")]
  public static extern global::System.IntPtr SolveStatus_OptimalDecisionResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_SolveStatus_FailedResult")]
  public static extern global::System.IntPtr SolveStatus_FailedResult();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_SolveStatus_InvalidModelResult")]
  public static extern global::System.IntPtr SolveStatus_InvalidModelResult();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_SolveStatus_InvalidParameterResult")]
  public static extern global::System.IntPtr SolveStatus_InvalidParameterResult();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_SolveStatus_getStatus")]
  public static extern int SolveStatus_getStatus(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_SolveStatus_getBestAlternatives")]
  public static extern global::System.IntPtr SolveStatus_getBestAlternatives(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_SolveStatus")]
  public static extern global::System.IntPtr new_SolveStatus();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_SolveStatus")]
  public static extern void delete_SolveStatus(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_TaskStep__SWIG_0")]
  public static extern global::System.IntPtr new_TaskStep__SWIG_0(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_TaskStep__SWIG_1")]
  public static extern global::System.IntPtr new_TaskStep__SWIG_1(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskStep_TextType")]
  public static extern global::System.IntPtr TaskStep_TextType(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskStep_TablePartType")]
  public static extern global::System.IntPtr TaskStep_TablePartType(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskStep_EndTableType")]
  public static extern global::System.IntPtr TaskStep_EndTableType();

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskStep_StepType")]
  public static extern string TaskStep_StepType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_TaskStep_AsString")]
  public static extern string TaskStep_AsString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_TaskStep")]
  public static extern void delete_TaskStep(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_UncertaintyCriterion")]
  public static extern void delete_UncertaintyCriterion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_MaximinCriterion")]
  public static extern global::System.IntPtr new_MaximinCriterion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_MaximinCriterion_solve")]
  public static extern global::System.IntPtr MaximinCriterion_solve(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_MaximinCriterion")]
  public static extern void delete_MaximinCriterion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_OptimismPessimismCriterion")]
  public static extern global::System.IntPtr new_OptimismPessimismCriterion(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_OptimismPessimismCriterion_solve")]
  public static extern global::System.IntPtr OptimismPessimismCriterion_solve(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_OptimismPessimismCriterion")]
  public static extern void delete_OptimismPessimismCriterion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_PrincipleOfInsufficientReason")]
  public static extern global::System.IntPtr new_PrincipleOfInsufficientReason(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_PrincipleOfInsufficientReason_solve")]
  public static extern global::System.IntPtr PrincipleOfInsufficientReason_solve(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_PrincipleOfInsufficientReason")]
  public static extern void delete_PrincipleOfInsufficientReason(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_ProbabilityCriterion")]
  public static extern void delete_ProbabilityCriterion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_new_AverageResultCriterion")]
  public static extern global::System.IntPtr new_AverageResultCriterion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AverageResultCriterion_solve")]
  public static extern global::System.IntPtr AverageResultCriterion_solve(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_delete_AverageResultCriterion")]
  public static extern void delete_AverageResultCriterion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_UncertaintyCriterion_SWIGUpcast")]
  public static extern global::System.IntPtr UncertaintyCriterion_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_MaximinCriterion_SWIGUpcast")]
  public static extern global::System.IntPtr MaximinCriterion_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_OptimismPessimismCriterion_SWIGUpcast")]
  public static extern global::System.IntPtr OptimismPessimismCriterion_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_PrincipleOfInsufficientReason_SWIGUpcast")]
  public static extern global::System.IntPtr PrincipleOfInsufficientReason_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_ProbabilityCriterion_SWIGUpcast")]
  public static extern global::System.IntPtr ProbabilityCriterion_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("libnatural_uncertainty", EntryPoint="CSharp_NaturalUncertaintyCsharpApi_AverageResultCriterion_SWIGUpcast")]
  public static extern global::System.IntPtr AverageResultCriterion_SWIGUpcast(global::System.IntPtr jarg1);
}

}
