//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NaturalUncertaintyCsharpApi {

public class SolveStatus : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SolveStatus(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SolveStatus obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SolveStatus obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SolveStatus() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          natural_uncertainty_libPINVOKE.delete_SolveStatus(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static SolveStatus OptimalDecisionResult(IntList bestAlternativeNum) {
    SolveStatus ret = new SolveStatus(natural_uncertainty_libPINVOKE.SolveStatus_OptimalDecisionResult(IntList.getCPtr(bestAlternativeNum)), true);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SolveStatus FailedResult() {
    SolveStatus ret = new SolveStatus(natural_uncertainty_libPINVOKE.SolveStatus_FailedResult(), true);
    return ret;
  }

  public static SolveStatus InvalidModelResult() {
    SolveStatus ret = new SolveStatus(natural_uncertainty_libPINVOKE.SolveStatus_InvalidModelResult(), true);
    return ret;
  }

  public static SolveStatus InvalidParameterResult() {
    SolveStatus ret = new SolveStatus(natural_uncertainty_libPINVOKE.SolveStatus_InvalidParameterResult(), true);
    return ret;
  }

  public Status getStatus() {
    Status ret = (Status)natural_uncertainty_libPINVOKE.SolveStatus_getStatus(swigCPtr);
    return ret;
  }

  public IntList getBestAlternatives() {
    IntList ret = new IntList(natural_uncertainty_libPINVOKE.SolveStatus_getBestAlternatives(swigCPtr), true);
    return ret;
  }

  public SolveStatus() : this(natural_uncertainty_libPINVOKE.new_SolveStatus(), true) {
  }

}

}
