//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NaturalUncertaintyCsharpApi {

public class TaskProcess : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<TaskStep>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TaskProcess(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TaskProcess obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TaskProcess obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TaskProcess() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          natural_uncertainty_libPINVOKE.delete_TaskProcess(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TaskProcess(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (TaskStep element in c) {
      this.Add(element);
    }
  }

  public TaskProcess(global::System.Collections.Generic.IEnumerable<TaskStep> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (TaskStep element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public TaskStep this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(TaskStep[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(TaskStep[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, TaskStep[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public TaskStep[] ToArray() {
    TaskStep[] array = new TaskStep[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<TaskStep> global::System.Collections.Generic.IEnumerable<TaskStep>.GetEnumerator() {
    return new TaskProcessEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new TaskProcessEnumerator(this);
  }

  public TaskProcessEnumerator GetEnumerator() {
    return new TaskProcessEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class TaskProcessEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<TaskStep>
  {
    private TaskProcess collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public TaskProcessEnumerator(TaskProcess collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public TaskStep Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (TaskStep)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public TaskProcess() : this(natural_uncertainty_libPINVOKE.new_TaskProcess__SWIG_0(), true) {
  }

  public TaskProcess(TaskProcess other) : this(natural_uncertainty_libPINVOKE.new_TaskProcess__SWIG_1(TaskProcess.getCPtr(other)), true) {
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    natural_uncertainty_libPINVOKE.TaskProcess_Clear(swigCPtr);
  }

  public void Add(TaskStep x) {
    natural_uncertainty_libPINVOKE.TaskProcess_Add(swigCPtr, TaskStep.getCPtr(x));
  }

  private uint size() {
    uint ret = natural_uncertainty_libPINVOKE.TaskProcess_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = natural_uncertainty_libPINVOKE.TaskProcess_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = natural_uncertainty_libPINVOKE.TaskProcess_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    natural_uncertainty_libPINVOKE.TaskProcess_reserve(swigCPtr, n);
  }

  public TaskProcess(int capacity) : this(natural_uncertainty_libPINVOKE.new_TaskProcess__SWIG_2(capacity), true) {
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  private TaskStep getitemcopy(int index) {
    global::System.IntPtr cPtr = natural_uncertainty_libPINVOKE.TaskProcess_getitemcopy(swigCPtr, index);
    TaskStep ret = (cPtr == global::System.IntPtr.Zero) ? null : new TaskStep(cPtr, false);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private TaskStep getitem(int index) {
    global::System.IntPtr cPtr = natural_uncertainty_libPINVOKE.TaskProcess_getitem(swigCPtr, index);
    TaskStep ret = (cPtr == global::System.IntPtr.Zero) ? null : new TaskStep(cPtr, false);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, TaskStep val) {
    natural_uncertainty_libPINVOKE.TaskProcess_setitem(swigCPtr, index, TaskStep.getCPtr(val));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(TaskProcess values) {
    natural_uncertainty_libPINVOKE.TaskProcess_AddRange(swigCPtr, TaskProcess.getCPtr(values));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public TaskProcess GetRange(int index, int count) {
    global::System.IntPtr cPtr = natural_uncertainty_libPINVOKE.TaskProcess_GetRange(swigCPtr, index, count);
    TaskProcess ret = (cPtr == global::System.IntPtr.Zero) ? null : new TaskProcess(cPtr, true);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, TaskStep x) {
    natural_uncertainty_libPINVOKE.TaskProcess_Insert(swigCPtr, index, TaskStep.getCPtr(x));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, TaskProcess values) {
    natural_uncertainty_libPINVOKE.TaskProcess_InsertRange(swigCPtr, index, TaskProcess.getCPtr(values));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    natural_uncertainty_libPINVOKE.TaskProcess_RemoveAt(swigCPtr, index);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    natural_uncertainty_libPINVOKE.TaskProcess_RemoveRange(swigCPtr, index, count);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public static TaskProcess Repeat(TaskStep value, int count) {
    global::System.IntPtr cPtr = natural_uncertainty_libPINVOKE.TaskProcess_Repeat(TaskStep.getCPtr(value), count);
    TaskProcess ret = (cPtr == global::System.IntPtr.Zero) ? null : new TaskProcess(cPtr, true);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    natural_uncertainty_libPINVOKE.TaskProcess_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    natural_uncertainty_libPINVOKE.TaskProcess_Reverse__SWIG_1(swigCPtr, index, count);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, TaskProcess values) {
    natural_uncertainty_libPINVOKE.TaskProcess_SetRange(swigCPtr, index, TaskProcess.getCPtr(values));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(TaskStep value) {
    bool ret = natural_uncertainty_libPINVOKE.TaskProcess_Contains(swigCPtr, TaskStep.getCPtr(value));
    return ret;
  }

  public int IndexOf(TaskStep value) {
    int ret = natural_uncertainty_libPINVOKE.TaskProcess_IndexOf(swigCPtr, TaskStep.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(TaskStep value) {
    int ret = natural_uncertainty_libPINVOKE.TaskProcess_LastIndexOf(swigCPtr, TaskStep.getCPtr(value));
    return ret;
  }

  public bool Remove(TaskStep value) {
    bool ret = natural_uncertainty_libPINVOKE.TaskProcess_Remove(swigCPtr, TaskStep.getCPtr(value));
    return ret;
  }

}

}
