//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NaturalUncertaintyCsharpApi {

public class UncertaintyList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Uncertainty>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UncertaintyList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UncertaintyList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(UncertaintyList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~UncertaintyList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libnatural_uncertaintyPINVOKE.delete_UncertaintyList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UncertaintyList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Uncertainty element in c) {
      this.Add(element);
    }
  }

  public UncertaintyList(global::System.Collections.Generic.IEnumerable<Uncertainty> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Uncertainty element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Uncertainty this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Uncertainty[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Uncertainty[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Uncertainty[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Uncertainty[] ToArray() {
    Uncertainty[] array = new Uncertainty[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Uncertainty> global::System.Collections.Generic.IEnumerable<Uncertainty>.GetEnumerator() {
    return new UncertaintyListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new UncertaintyListEnumerator(this);
  }

  public UncertaintyListEnumerator GetEnumerator() {
    return new UncertaintyListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class UncertaintyListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Uncertainty>
  {
    private UncertaintyList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public UncertaintyListEnumerator(UncertaintyList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Uncertainty Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Uncertainty)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public UncertaintyList() : this(libnatural_uncertaintyPINVOKE.new_UncertaintyList__SWIG_0(), true) {
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public UncertaintyList(UncertaintyList other) : this(libnatural_uncertaintyPINVOKE.new_UncertaintyList__SWIG_1(UncertaintyList.getCPtr(other)), true) {
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    libnatural_uncertaintyPINVOKE.UncertaintyList_Clear(swigCPtr);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(Uncertainty x) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_Add(swigCPtr, Uncertainty.getCPtr(x));
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = libnatural_uncertaintyPINVOKE.UncertaintyList_size(swigCPtr);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = libnatural_uncertaintyPINVOKE.UncertaintyList_empty(swigCPtr);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = libnatural_uncertaintyPINVOKE.UncertaintyList_capacity(swigCPtr);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_reserve(swigCPtr, n);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public UncertaintyList(int capacity) : this(libnatural_uncertaintyPINVOKE.new_UncertaintyList__SWIG_2(capacity), true) {
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  private Uncertainty getitemcopy(int index) {
    Uncertainty ret = new Uncertainty(libnatural_uncertaintyPINVOKE.UncertaintyList_getitemcopy(swigCPtr, index), true);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Uncertainty getitem(int index) {
    Uncertainty ret = new Uncertainty(libnatural_uncertaintyPINVOKE.UncertaintyList_getitem(swigCPtr, index), false);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Uncertainty val) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_setitem(swigCPtr, index, Uncertainty.getCPtr(val));
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(UncertaintyList values) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_AddRange(swigCPtr, UncertaintyList.getCPtr(values));
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public UncertaintyList GetRange(int index, int count) {
    global::System.IntPtr cPtr = libnatural_uncertaintyPINVOKE.UncertaintyList_GetRange(swigCPtr, index, count);
    UncertaintyList ret = (cPtr == global::System.IntPtr.Zero) ? null : new UncertaintyList(cPtr, true);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Uncertainty x) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_Insert(swigCPtr, index, Uncertainty.getCPtr(x));
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, UncertaintyList values) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_InsertRange(swigCPtr, index, UncertaintyList.getCPtr(values));
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_RemoveAt(swigCPtr, index);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_RemoveRange(swigCPtr, index, count);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public static UncertaintyList Repeat(Uncertainty value, int count) {
    global::System.IntPtr cPtr = libnatural_uncertaintyPINVOKE.UncertaintyList_Repeat(Uncertainty.getCPtr(value), count);
    UncertaintyList ret = (cPtr == global::System.IntPtr.Zero) ? null : new UncertaintyList(cPtr, true);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libnatural_uncertaintyPINVOKE.UncertaintyList_Reverse__SWIG_0(swigCPtr);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_Reverse__SWIG_1(swigCPtr, index, count);
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, UncertaintyList values) {
    libnatural_uncertaintyPINVOKE.UncertaintyList_SetRange(swigCPtr, index, UncertaintyList.getCPtr(values));
    if (libnatural_uncertaintyPINVOKE.SWIGPendingException.Pending) throw libnatural_uncertaintyPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
