//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class AlternativeList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Alternative>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AlternativeList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AlternativeList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AlternativeList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AlternativeList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          natural_uncertainty_libPINVOKE.delete_AlternativeList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public AlternativeList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Alternative element in c) {
      this.Add(element);
    }
  }

  public AlternativeList(global::System.Collections.Generic.IEnumerable<Alternative> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Alternative element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Alternative this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Alternative[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Alternative[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Alternative[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Alternative[] ToArray() {
    Alternative[] array = new Alternative[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Alternative> global::System.Collections.Generic.IEnumerable<Alternative>.GetEnumerator() {
    return new AlternativeListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new AlternativeListEnumerator(this);
  }

  public AlternativeListEnumerator GetEnumerator() {
    return new AlternativeListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class AlternativeListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Alternative>
  {
    private AlternativeList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public AlternativeListEnumerator(AlternativeList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Alternative Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Alternative)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public AlternativeList() : this(natural_uncertainty_libPINVOKE.new_AlternativeList__SWIG_0(), true) {
  }

  public AlternativeList(AlternativeList other) : this(natural_uncertainty_libPINVOKE.new_AlternativeList__SWIG_1(AlternativeList.getCPtr(other)), true) {
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    natural_uncertainty_libPINVOKE.AlternativeList_Clear(swigCPtr);
  }

  public void Add(Alternative x) {
    natural_uncertainty_libPINVOKE.AlternativeList_Add(swigCPtr, Alternative.getCPtr(x));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = natural_uncertainty_libPINVOKE.AlternativeList_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = natural_uncertainty_libPINVOKE.AlternativeList_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = natural_uncertainty_libPINVOKE.AlternativeList_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    natural_uncertainty_libPINVOKE.AlternativeList_reserve(swigCPtr, n);
  }

  public AlternativeList(int capacity) : this(natural_uncertainty_libPINVOKE.new_AlternativeList__SWIG_2(capacity), true) {
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  private Alternative getitemcopy(int index) {
    Alternative ret = new Alternative(natural_uncertainty_libPINVOKE.AlternativeList_getitemcopy(swigCPtr, index), true);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Alternative getitem(int index) {
    Alternative ret = new Alternative(natural_uncertainty_libPINVOKE.AlternativeList_getitem(swigCPtr, index), false);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Alternative val) {
    natural_uncertainty_libPINVOKE.AlternativeList_setitem(swigCPtr, index, Alternative.getCPtr(val));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(AlternativeList values) {
    natural_uncertainty_libPINVOKE.AlternativeList_AddRange(swigCPtr, AlternativeList.getCPtr(values));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public AlternativeList GetRange(int index, int count) {
    global::System.IntPtr cPtr = natural_uncertainty_libPINVOKE.AlternativeList_GetRange(swigCPtr, index, count);
    AlternativeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new AlternativeList(cPtr, true);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Alternative x) {
    natural_uncertainty_libPINVOKE.AlternativeList_Insert(swigCPtr, index, Alternative.getCPtr(x));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, AlternativeList values) {
    natural_uncertainty_libPINVOKE.AlternativeList_InsertRange(swigCPtr, index, AlternativeList.getCPtr(values));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    natural_uncertainty_libPINVOKE.AlternativeList_RemoveAt(swigCPtr, index);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    natural_uncertainty_libPINVOKE.AlternativeList_RemoveRange(swigCPtr, index, count);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public static AlternativeList Repeat(Alternative value, int count) {
    global::System.IntPtr cPtr = natural_uncertainty_libPINVOKE.AlternativeList_Repeat(Alternative.getCPtr(value), count);
    AlternativeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new AlternativeList(cPtr, true);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    natural_uncertainty_libPINVOKE.AlternativeList_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    natural_uncertainty_libPINVOKE.AlternativeList_Reverse__SWIG_1(swigCPtr, index, count);
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, AlternativeList values) {
    natural_uncertainty_libPINVOKE.AlternativeList_SetRange(swigCPtr, index, AlternativeList.getCPtr(values));
    if (natural_uncertainty_libPINVOKE.SWIGPendingException.Pending) throw natural_uncertainty_libPINVOKE.SWIGPendingException.Retrieve();
  }

}
